### PR TITLE
Modular imports for lodash.

### PR DESCRIPTION
**Pull request by ascariandrea**
In this pr I also removed useless methods like `merge` substituting with `es6` spread operators. 
Let me know, thanks.

### CODE REVIEW

**Comment by boygirl** [comment]
@ascariandrea actually, I think there is a difference in how `_.merge` and spread operators handle undefined values, so please leave that one in for now. I think it will need to be replaced with a little bit of caution.

**Comment by boygirl** [comment]
Thank you for replacing things like `map` and `each` though

**Comment by ascariandrea** [comment]
You're right, I didn't consider that case.

**Comment by boygirl** [comment]
@ascariandrea thanks!

**Comment by ascariandrea** [comment]
@boygirl You're welcome!

**Pull request merged**
